fix elasticsearch

diff --git a/.github/workflows/search-ci.yaml b/.github/workflows/search-ci.yaml
--- a/.github/workflows/search-ci.yaml
+++ b/.github/workflows/search-ci.yaml
@@ -26,11 +26,11 @@ jobs:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-      # - name: Gitleaks Scan
-      #   if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
-      #   uses: gitleaks/gitleaks-action@v2
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Gitleaks Scan
+        if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
+        uses: gitleaks/gitleaks-action@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
   build:
     runs-on: ubuntu-latest
@@ -38,8 +38,6 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/workflows/actions
-      # - name: Configure sysctl limits for Elasticsearch
-      #   run: sudo sysctl -w vm.max_map_count=262144
       - name: Run Maven Build Command
         run: mvn clean install -pl search -am
       
@@ -75,6 +73,7 @@ jobs:
           -Dsonar.token=$SONAR_TOKEN 
           -Dsonar.coverage.jacoco.xmlReportPaths=${{github.workspace}}/search/target/site/jacoco/jacoco.xml
       - name: Add coverage report to PR
+        id: jacoco_reporter
         uses: madrapps/jacoco-report@v1.6.1
         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
         with:
@@ -84,21 +83,33 @@ jobs:
           min-coverage-changed-files: 70
           title: 'Search Coverage Report'
           update-comment: true
+      
+      - name: Coverage check
+        run: |
+          OVERALL=${{ steps.jacoco_reporter.outputs['coverage-overall'] }}
+          echo "Current Overall Coverage is: $OVERALL%"
+          
+          if (( $(echo "$OVERALL < 70.0" | bc -l) )); then
+            echo "Error: Code Coverage ($OVERALL%) is lower than set standards (70%)!"
+            exit 1 
+          else
+            echo "Code Coverage Pass"
+          fi
           
   security:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      # - name: Run Snyk to check for vulnerabilities
-      #   uses: snyk/actions/maven@master
-      #   continue-on-error: true
-      #   env:
-      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
-      #   with:
-      #     args: --sarif-file-output=snyk.sarif
+      - name: Run Snyk to check for vulnerabilities
+        uses: snyk/actions/maven@master
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        with:
+          args: --sarif-file-output=snyk.sarif
 
-      # - name: Upload result to GitHub Code Scanning
-      #   uses: github/codeql-action/upload-sarif@v3
-      #   with:
-      #     sarif_file: snyk.sarif
+      - name: Upload result to GitHub Code Scanning
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
   
