Update webhook-ci.yaml

diff --git a/.github/workflows/webhook-ci.yaml b/.github/workflows/webhook-ci.yaml
--- a/.github/workflows/webhook-ci.yaml
+++ b/.github/workflows/webhook-ci.yaml
@@ -66,13 +66,14 @@ jobs:
         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f webhook
+        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -pl webhook -am
           -Dsonar.projectKey=thanhdatttt_DevOps-Project
           -Dsonar.organization=thanhdatttt
           -Dsonar.host.url=https://sonarcloud.io
           -Dsonar.token=$SONAR_TOKEN 
           -Dsonar.coverage.jacoco.xmlReportPaths=${{github.workspace}}/webhook/target/site/jacoco/jacoco.xml
       - name: Add coverage report to PR
+        id: jacoco_reporter
         uses: madrapps/jacoco-report@v1.6.1
         if: ${{ env.FROM_ORIGINAL_REPOSITORY == 'true' }}
         with:
@@ -82,6 +83,18 @@ jobs:
           min-coverage-changed-files: 70
           title: 'Webhook Coverage Report'
           update-comment: true
+
+      - name: Coverage check
+        run: |
+          OVERALL=${{ steps.jacoco_reporter.outputs['coverage-overall'] }}
+          echo "Current Overall Coverage is: $OVERALL%"
+          
+          if (( $(echo "$OVERALL < 70.0" | bc -l) )); then
+            echo "Error: Code Coverage ($OVERALL%) is lower than set standards (70%)!"
+            exit 1 
+          else
+            echo "Code Coverage Pass"
+          fi
           
   security:
     runs-on: ubuntu-latest
